spring:
  application:
    name: pangea
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver 
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  sql:
    init:
      mode: always
      separator: ^^^ END OF SCRIPT ^^^
      schema-locations:
        - classpath:sql/initializer.sql
        - classpath:sql/tables/tables.sql
        - classpath:sql/triggers/insert-role-after-user.sql
        - classpath:sql/mocks/mocks.sql
      # continue-on-error: true
