server:
  port: 8080
  shutdown: immediate

spring:
  application:
    name: pangea
  datasource:
    url: ${DB_URL}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver 
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  sql:
    init:
      mode: always
      separator: ^^^ END OF SCRIPT ^^^
      schema-locations:
        - classpath:sql/initializer.sql
        - classpath:sql/tables/tables.sql
        - classpath:sql/triggers/insert-role-after-user.sql
        # - classpath:sql/mocks/mocks.sql
      # continue-on-error: true
  # profiles:
  #   active: gh-action
management:
  endpoints:
    web:
      exposure:
        include: "*"