name: Build app

on:
  workflow_call:

jobs:
  build-app:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USERNAME: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_DATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checking repository...
        uses: actions/checkout@v4
      - name: Installing java..
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: "maven"
      - name: Packaging...
        run: |
          mvn clean package --file pom.xml
      - name: Run app...
        run: |
          java -jar target/pangea.jar
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          spring.profiles.active: gh-action
      - name: Success...
        run: |
          echo "Workflow success..."


          
  
      